### ISSUE TITLE
New message event callback

### ISSUE THREAD

**Issue by ahgray123** [GetStream/stream-chat-unity#25]
In `StreamChatClient` in the `RegisterEventHandlers` method, the message event registration appears thus:

`RegisterEventType<EventMessageNewDTO, EventMessageNew>(EventType.MessageNew,
                e => MessageReceived?.Invoke(e));`

However, the event that comes from the web socket is actually an `EventType.NotificationMessageNew`, which means we don't get a callback on the `MessageReceived` event handler.

**Comment by sierpinskid** [comment]
Hi, thank you for your contribution!

So there are 2 events notifying you about the new message:
`EventType.MessageNew` - triggered by new messages on watched channels regardless if you are a member or not
`EventType.NotificationMessageNew` - triggered by new messages on non-watched channels but only if you are a member of that channel

So the MessageReceived event will be triggered for a new message if you watch a channel.

How to watch a channel?
1. QueryChannelsRequest watches them by default because QueryChannelsRequest object has a `Watch` property = true
2. you can also use `StreamChatClient.ChannelApi.GetOrCreateChannelAsync` but in ChannelGetOrCreateRequest you need to set `Watch` property = true

I'll add support for the `EventType.NotificationMessageNew` event with a proper description so it's clear. 

You can read [more on events here](https://getstream.io/chat/docs/unity/event_object/?language=unity)

**Comment by ahgray123** [comment]
Fantastic! Thanks so much for this. That makes perfect sense. I had previously set up channels with watchers, but in my cleanup code, I had commented that out. I'll add it back in and should be good to go.
