### ISSUE TITLE
Instructions for setting Test User ID?

### ISSUE THREAD

**Issue by tomkail** [GetStream/stream-chat-unity#7]
This isn't really explained anywhere in the Stream Unity docs, and it'd be super handy, since the demo scene doesn't run without them! 
The dashboard provides a bunch of different keys and things, but it's not really detailed which of these Unity needs, and how to generate a new User ID (as I believe I need to do?)
[I've found this, but it's a bit hidden away and isn't entirely useful](https://getstream.io/chat/docs/unity/tokens_and_authentication/?language=csharp).

**Comment by sierpinskid** [comment]
Thanks! 
Highly appreciate this kind of feedback. I was already concerned that this might be a little confusing to new Unity users. I'll improve the docs and was also planning on adding a setup wizard that would launch when SDK is imported and guide in the setup process. 

But to answer your question:
Yes, you need to create a user in order to log into Stream Chat. Every user requires a dedicated user authorization token.

How it works:

**Production mode:**
You set up a backend that uses one of our server-side SDKs in order to generate user tokens. The token for a particular user is sent to the Unity client when the user is registered and the auth token is used by Unity SDK to authorize the chat access. For security reasons, tokens can be only generated server-side (otherwise player might decompile the game and obtain the API secret key).

**Development mode:**
1. Manually creating users and user tokens:
Test users can be created in the [Stream App Dashboard](https://dashboard.getstream.io/) (Dashboard -> Explorer -> users -> Create new user) and by using _user id_ and the _api secret key_ you can generate _auth tokens_ in the [Online Token Generator](https://getstream.io/chat/docs/unity/tokens_and_authentication/?language=unity#manually-generating-tokens)
2. Disabling auth checks and using dev tokens
[Developer Tokens](https://getstream.io/chat/docs/react/tokens_and_authentication/#developer-tokens) are not yet implemented in Unity SDK but will be added in the future

So for now the only developemt/testing option without setting up server-side token generation is to create users in the [Stream App Dashboard](https://dashboard.getstream.io/) (Dashboard -> Explorer -> users) and use  [Online Token Generator](https://getstream.io/chat/docs/unity/tokens_and_authentication/?language=unity#manually-generating-tokens) to get the auth token

**Comment by tomkail** [comment]
Right back at you! We're testing a bunch of chat solutions in Unity and Stream is the only one that replies to issues on git, I'm sure we'll have more feedback if we go your way! Anyhoo - 

Dev mode - Thanks for those links! I completely failed to navigate the dashboard and the docs. I'd not even realised that this app name was clickable! That might be my problem :D
![image](https://user-images.githubusercontent.com/1252816/162689991-2025cc10-8659-4aa7-9666-b7ba852e0e53.png)

For production keys, can I suggest a REST client or something that could be called from Unity without faffing around with our own server side stuff? PHP still gives me nightmares.
