### ISSUE TITLE
implement friend system. 

### ISSUE THREAD

**Issue by smile930307** [GetStream/stream-chat-unity#71]
I need to implement friend system,
How can I get if I sent friend request to the user as reaction and the user also sent the friend request to me or accepted my friend request?
In one word, how will we implement the friend request each other?

**Comment by sierpinskid** [comment]
Hi, thank you for using Stream! 
Stream Chat API doesn't offer a dedicated friends system but it should be possible to achieve a simple friends system that allows users to have their friends list with online presence shown and be notified when their friends become online.

It could be achieved this way:
- For each user, you'd have a dedicated channel that represents their friends' list
- "friend request" would use our [Invites System](https://getstream.io/chat/docs/unity/channel_invites/?language=unity) so whenever a user wants to send a friend request he would invite the other user to his personal friends list channel
- Whenever friend `A` confirms friend request sent by user `B` your backend solution would use our backend SDK to add both users to `A` and `B` friend lists channel (so both friends have themselves added to their friends' list)
- This way each user has a friend list with their online status and can react to `user.presence.changed` event in order to show a notification that a friend went online
- Also to make sure this special friends list channel is only used for maintaining a friends list and not for chatting you could create a custom channel type in [Stream Dashboard](https://dashboard.getstream.io/) (Dashboard -> App -> Channel Types) and set permissions (Dashboard -> App -> Roles & Permissions) for this channel to disallow actions like `Create Message` and `Create Message in Owned Channel` so that no one can send any messages to this channel.
