### ISSUE TITLE
CustomData.Get<T>() is nice, but is there chance for any kind of Set<T>()?

### ISSUE THREAD

**Issue by zbigniewcebula** [GetStream/stream-chat-unity#73]
It would be cool to have Set<T>() method for CustomData of the channels, members etc.
But assuming that would be better option to batch the queries, Set<T>() could serialize and prepare data, but if a user wants it to be sent, some kind of "Update/Upsert Changes" would resolve the need for updating data, while having few different types saved using Set<T>().

**Comment by sierpinskid** [comment]
Hi,
Thank you for your contribution!

> But assuming that would be better option to batch the queries

This is exactly why `Set<T>()` was not introduced in the first place. Every call would execute an API call under the hood which could potentially lead to unexpectedly high usage of the limits. One of the core rules we follow is to use the user API as optimally as possible in order to reduce the chat operations cost for our customers.

> Set() could serialize and prepare data, but if a user wants it to be sent, some kind of "Update/Upsert Changes" would resolve the need for updating data,

This is theoretically possible but there are 2 problems with this approach:
1. If `Set<T>()` doesn't update the remote data but only caches the changes until you flush them with the "Update/Upsert" call, you now have a state mismatch between the local state and the remote state on the server. It seems most intuitive and least error-prone if the local state always reflects the state on the server. Depending on how custom data is used this could lead to situations where chat users see different states of the chat. 
2. If the remote update is deferred you might lose those changes if the chat user closes the app before cached changes are sent to the server.

I'll look into your request and research ways to simplify setting the custom data.

Thanks again for your input!
