### ISSUE TITLE
File API?

### ISSUE THREAD

**Issue by tomkail** [GetStream/stream-chat-unity#8]
I just tried using the C# file API example but it seems not to be implemented. Any word on when this'll be done, and what it'll support? We're ideally interested in the ability for users to record and send video messages. Ta!

**Comment by sierpinskid** [comment]
in general, we strongly sort and adjust the roadmap according to our customer's needs. 

File API was not a high priority for now because it's not a common use case in game dev. 

Although if it's something you need I can add support for it very fast, after all the backend functionality is there and is widely used by our customers using other SDKs, so it's only the endpoints support on the Unity SDK side that is missing.

Regarding functionality please refer to this page:
https://getstream.io/chat/docs/unity/file_uploads/?language=unity

Unity examples are not available yet but the functionality will be very similar to how it works in our other SDK.

General overview:
- players can send message attachments up to 100MB
- any file type is allowed, but image types have extra features available like image resizing
- In your dashboard, there is a section called "Upload Configuration" which allows defining what extensions of files are allowed

**Comment by tomkail** [comment]
Cool, thanks! This would be _very_ useful for us, since you have a serious edge over PubNub's 5mb file limit! We're looking for users to share video messages, so file size is a big deal for us!

**Comment by sierpinskid** [comment]
I've added endpoints for file upload/delete. Check out [the documentation](https://getstream.io/chat/docs/unity/file_uploads/?language=unity) for code samples.

I've also added video attachments to the sample project (note that the file picker works only in the Unity Editor atm). Video attachments are presented as a video component.

Thanks for your contribution! :)
